# Numpy基础教程

## 1 NumPy Ndarray

### 1.1 创建Ndarray对象

#### 一般数组

In [3]:
import numpy as np

In [13]:
arr = np.array(range(10)).reshape(1,2,5)
arr

array([[[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]]])

In [14]:
# 元素类型
arr.dtype

dtype('int64')

In [15]:
# 数组维数(秩)
arr.ndim

3

In [16]:
# 大小
arr.size

10

In [17]:
len(arr)

1

In [18]:
# 形状
arr.shape

(1, 2, 5)

In [19]:
# 每个元素的字节数
arr.itemsize

8

In [15]:
# 内存信息
arr.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

In [16]:
# 元素实部
arr.real

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int8)

In [17]:
# 元素虚部
arr.imag

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int8)

In [18]:
# 缓冲区数据
arr.data

In [26]:
arr = np.array(range(1,10), dtype='f4')

In [27]:
arr

array([1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=float32)

In [31]:
arr2 = arr.reshape(3,3)
arr2

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]], dtype=float32)

In [32]:
arr2.ndim

2

In [34]:
arr2.shape

(3, 3)

In [35]:
arr2.size

9

In [36]:
len(arr2)

3

In [38]:
arr2.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : False
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

In [39]:
arr2.dtype

dtype('float32')

In [40]:
arr2.itemsize

4

In [42]:
arr3 = np.array([(1,12,13),(21,22,23)])

In [43]:
arr3

array([[ 1, 12, 13],
       [21, 22, 23]])

In [45]:
arr4 = np.array([[1,12,13,14],(21, 22, 23, 24)], dtype=np.int32)
arr4

array([[ 1, 12, 13, 14],
       [21, 22, 23, 24]], dtype=int32)

In [48]:
arr5 = np.array(arr4, dtype=complex)
arr5

array([[ 1.+0.j, 12.+0.j, 13.+0.j, 14.+0.j],
       [21.+0.j, 22.+0.j, 23.+0.j, 24.+0.j]])

In [51]:
arr5.dtype

dtype('complex128')

In [50]:
arr6 = np.array(arr4, dtype='c8')
arr6

array([[ 1.+0.j, 12.+0.j, 13.+0.j, 14.+0.j],
       [21.+0.j, 22.+0.j, 23.+0.j, 24.+0.j]], dtype=complex64)

In [52]:
arr6.dtype

dtype('complex64')

In [60]:
arr7 = np.array([['A1','B1','C1','D1'],
                 ['A2','B2','C2','D2'],
                 ['A3','B3','C3','D3']
                ],dtype='U')
arr7

array([['A1', 'B1', 'C1', 'D1'],
       ['A2', 'B2', 'C2', 'D2'],
       ['A3', 'B3', 'C3', 'D3']], dtype='<U2')

In [61]:
arr7.dtype

dtype('<U2')

#### 特殊数组

In [20]:
# 全零数组
zeros = np.zeros((3,4))
zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [21]:
zeros.dtype

dtype('float64')

In [22]:
zeros = np.zeros((5,6), dtype='i1')
zeros

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]], dtype=int8)

In [69]:
# 单位矩阵
identity = np.eye(6, dtype='i2')
identity

array([[1, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0],
       [0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 1]], dtype=int16)

In [72]:
# 全1矩阵
diag = np.ones((3,4), dtype='f2')
diag

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float16)

In [79]:
# 范围矩阵
numbers = np.arange(16, dtype='u1').reshape(4,4)
numbers

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]], dtype=uint8)

In [80]:
numbers.dtype

dtype('uint8')

In [81]:
numbers.size

16

In [82]:
len(numbers)

4

In [84]:
# 0~50之间的偶数
evens = np.arange(0, 50, 2, dtype='u2').reshape(5,5)
evens

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28],
       [30, 32, 34, 36, 38],
       [40, 42, 44, 46, 48]], dtype=uint16)

In [24]:
# 等差数列
x = np.linspace(1, 10, 12) # 0~10之间的10个数
x

array([ 1.        ,  1.81818182,  2.63636364,  3.45454545,  4.27272727,
        5.09090909,  5.90909091,  6.72727273,  7.54545455,  8.36363636,
        9.18181818, 10.        ])

In [99]:
x = np.linspace(np.pi, np.pi * 10, 10)
x

array([ 3.14159265,  6.28318531,  9.42477796, 12.56637061, 15.70796327,
       18.84955592, 21.99114858, 25.13274123, 28.27433388, 31.41592654])

In [176]:
x = np.linspace(1,8,8, dtype=np.int8)
x

array([1, 2, 3, 4, 5, 6, 7, 8], dtype=int8)

In [177]:
x.reshape(2,4)

array([[1, 2, 3, 4],
       [5, 6, 7, 8]], dtype=int8)

In [25]:
x.shape

(12,)

In [27]:
12 == (12,)

False

In [172]:
x.dtype

dtype('int8')

In [28]:
y = np.logspace(1, 10, 10, dtype=int)
y

array([         10,         100,        1000,       10000,      100000,
           1000000,    10000000,   100000000,  1000000000, 10000000000])

In [182]:
y = np.logspace(1, 10, 10, base=2, dtype='u2')
y

array([   2,    4,    8,   16,   32,   64,  128,  256,  512, 1024],
      dtype=uint16)

In [123]:
# 随机数组
rnd_numbers = np.floor(10 * np.random.random((3,4)))
rnd_numbers

array([[1., 1., 3., 5.],
       [4., 6., 9., 2.],
       [3., 7., 9., 3.]])

In [124]:
# 泛化指定形状的数组
rnd_numbers.reshape(4,3)

array([[1., 1., 3.],
       [5., 4., 6.],
       [9., 2., 3.],
       [7., 9., 3.]])

In [125]:
rnd_numbers

array([[1., 1., 3., 5.],
       [4., 6., 9., 2.],
       [3., 7., 9., 3.]])

In [134]:
# 重设大小
rnd_numbers.resize(4,3)
rnd_numbers

array([[1., 1., 3.],
       [5., 4., 6.],
       [9., 2., 3.],
       [7., 9., 3.]])

In [29]:
# 创建未初始化数组
empty = np.empty((3,3))
empty

array([[2.04131324e-316, 6.93915896e-310, 6.93915802e-310],
       [6.93915899e-310, 6.93915775e-310, 6.93912709e-310],
       [6.93915793e-310, 6.93915532e-310, 3.95252517e-322]])

In [30]:
another = np.asarray(empty, dtype='i1')
another

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=int8)

In [32]:
# 从缓冲区创建数组
buffer = b'ABCDEFGHIJKLMN'
buf_arr = np.frombuffer(buffer, dtype='i1')
buf_arr

array([65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78], dtype=int8)

In [163]:
# 从迭代器创建数组
it = iter(range(ord('A'),ord('Z')))
it_arr = np.fromiter(it, dtype='S2')
it_arr

array([b'65', b'66', b'67', b'68', b'69', b'70', b'71', b'72', b'73',
       b'74', b'75', b'76', b'77', b'78', b'79', b'80', b'81', b'82',
       b'83', b'84', b'85', b'86', b'87', b'88', b'89'], dtype='|S2')

### 1.2 自定义类型

In [104]:
dt_u8 = np.dtype('u1')
dt_u8

dtype('uint8')

In [43]:
dt_book = np.dtype(
    [('name', 'U20'),
     ('author', 'U20'),
     ('price','f2')]
)
dt_book

dtype([('name', '<U20'), ('author', '<U20'), ('price', '<f2')])

In [44]:
books = np.array(
    [('Java','ZM',12.8),
     ('PHP','WX', 24.5),
     ('Python','XB', 45.5),
     ('HTML','FG', 34.4)]
    ,dtype= dt_book
)
books

array([('Java', 'ZM', 12.8), ('PHP', 'WX', 24.5), ('Python', 'XB', 45.5),
       ('HTML', 'FG', 34.4)],
      dtype=[('name', '<U20'), ('author', '<U20'), ('price', '<f2')])

In [45]:
books.dtype

dtype([('name', '<U20'), ('author', '<U20'), ('price', '<f2')])

In [46]:
books.size

4

In [39]:
books.itemsize

162

### 1.3 内置类型

In [184]:
np.dtype('i1')

dtype('int8')

In [188]:
np.dtype('b1')

dtype('bool')

In [189]:
np.dtype('b')

dtype('int8')

In [40]:
np.dtype('i')

dtype('int32')

In [199]:
np.dtype('i1')

dtype('int8')

In [200]:
np.dtype('i2')

dtype('int16')

In [201]:
np.dtype('i4')

dtype('int32')

In [202]:
np.dtype('i8')

dtype('int64')

In [192]:
np.dtype('u1')

dtype('uint8')

In [193]:
np.dtype('u2')

dtype('uint16')

In [194]:
np.dtype('u4')

dtype('uint32')

In [196]:
np.dtype('u8')

dtype('uint64')

In [205]:
np.dtype('f2')

dtype('float16')

In [206]:
np.dtype('f4')

dtype('float32')

In [207]:
np.dtype('f8')

dtype('float64')

In [208]:
np.dtype('f16')

dtype('float128')

In [213]:
np.dtype('c')

dtype('S1')

In [214]:
np.dtype('c8')

dtype('complex64')

In [216]:
np.dtype('c16')

dtype('complex128')

In [219]:
np.dtype('c32')

dtype('complex256')

In [221]:
np.dtype('m')

dtype('<m8')

In [222]:
np.dtype('M')

dtype('<M8')

In [223]:
np.dtype('O')

dtype('O')

In [228]:
np.dtype('M')

dtype('<M8')

In [229]:
np.dtype('S1')

dtype('S1')

In [230]:
np.dtype('S100')

dtype('S100')

In [231]:
np.dtype('a')

dtype('S')

In [232]:
np.dtype('a100')

dtype('S100')

In [235]:
np.dtype('U')

dtype('<U')

In [47]:
np.dtype('U100')

dtype('<U100')

### 1.4 切片与索引

In [259]:
rows = np.asarray([[i*10+n for n in range(0, 6)] for i in range(0, 6)])
rows

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

In [261]:
rows[0]

array([0, 1, 2, 3, 4, 5])

In [262]:
rows[:2]

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15]])

In [260]:
rows[2,3]

23

In [263]:
rows[2:]

array([[20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

In [264]:
rows[0:None:2]

array([[ 0,  1,  2,  3,  4,  5],
       [20, 21, 22, 23, 24, 25],
       [40, 41, 42, 43, 44, 45]])

In [265]:
rows[1:None:2]

array([[10, 11, 12, 13, 14, 15],
       [30, 31, 32, 33, 34, 35],
       [50, 51, 52, 53, 54, 55]])

In [266]:
rows[[5,3,1]]

array([[50, 51, 52, 53, 54, 55],
       [30, 31, 32, 33, 34, 35],
       [10, 11, 12, 13, 14, 15]])

In [267]:
rows[[5,3,1],[5,3,1]]

array([55, 33, 11])

In [268]:
rows[np.ix_([5,3,1],[5,3,1])]

array([[55, 53, 51],
       [35, 33, 31],
       [15, 13, 11]])

In [273]:
rows

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

In [279]:
row_indices=np.array([[0,0],[5,5]])
col_indices=np.array([[0,5],[0,5]])
rows[row_indices, col_indices]

array([[ 0,  5],
       [50, 55]])

In [280]:
rows[[1],[2]]

array([12])

In [281]:
rows[1][2]

12

In [282]:
rows[1,2]

12

In [283]:
rows[(1,2)]

12

In [284]:
rows[(1,),(2,)]

array([12])

In [287]:
rows[(1,1),(4,4)]

array([14, 14])

In [288]:
rows[[1,1],[4,4]]

array([14, 14])

In [290]:
rows[np.array([[1,1],[4,4]]),np.array([[1,4],[1,4]])]

array([[11, 14],
       [41, 44]])

In [292]:
rows[1:5,1:5]

array([[11, 12, 13, 14],
       [21, 22, 23, 24],
       [31, 32, 33, 34],
       [41, 42, 43, 44]])

In [295]:
rows[1:5, :]

array([[10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45]])

In [297]:
rows[1:5, [1,3,5]]

array([[11, 13, 15],
       [21, 23, 25],
       [31, 33, 35],
       [41, 43, 45]])

In [298]:
rows[:, [2,4]]

array([[ 2,  4],
       [12, 14],
       [22, 24],
       [32, 34],
       [42, 44],
       [52, 54]])

In [299]:
rows[..., [2, 4]]

array([[ 2,  4],
       [12, 14],
       [22, 24],
       [32, 34],
       [42, 44],
       [52, 54]])

In [301]:
rows[...,:]

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

In [302]:
rows[:]

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

In [303]:
rows[:,:]

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

In [304]:
rows[:,1:5]

array([[ 1,  2,  3,  4],
       [11, 12, 13, 14],
       [21, 22, 23, 24],
       [31, 32, 33, 34],
       [41, 42, 43, 44],
       [51, 52, 53, 54]])

In [305]:
rows[2:4,2:4]

array([[22, 23],
       [32, 33]])

In [309]:
rows[[2,3], [2,3]]

array([22, 33])

### 1.5 Numpy广播

In [3]:
a = np.array([1,2,3,4])
b = np.array([10,20,30,40])
c = a * b
c

array([ 10,  40,  90, 160])

In [50]:
a = np.array([[0, 0, 0],
              [10,10,10],
              [20,20,20],
              [30,30,30]
             ])
a

array([[ 0,  0,  0],
       [10, 10, 10],
       [20, 20, 20],
       [30, 30, 30]])

In [59]:
b = np.array([1,2,3,4]).reshape(4,1)
b

array([[1],
       [2],
       [3],
       [4]])

In [60]:
b.shape

(4, 1)

In [57]:
a.shape

(4, 3)

In [61]:
a + b

array([[ 1,  1,  1],
       [12, 12, 12],
       [23, 23, 23],
       [34, 34, 34]])

In [12]:
a

array([[ 0,  0,  0],
       [10, 10, 10],
       [20, 20, 20],
       [30, 30, 30]])

In [13]:
b

array([[1],
       [2],
       [3],
       [4]])

In [66]:
a.reshape(3,4)

array([[ 0,  0,  0, 10],
       [10, 10, 20, 20],
       [20, 30, 30, 30]])

In [67]:
a

array([[ 0,  0,  0],
       [10, 10, 10],
       [20, 20, 20],
       [30, 30, 30]])

In [68]:
a.shape = 3, 4

In [69]:
a

array([[ 0,  0,  0, 10],
       [10, 10, 20, 20],
       [20, 30, 30, 30]])

In [70]:
a.flat

In [80]:
type(a.flat)

numpy.flatiter

In [81]:
type(a.flatten())

numpy.ndarray

In [83]:
a.flatten('C')

array([ 0,  0,  0, 10, 10, 10, 20, 20, 20, 30, 30, 30])

In [79]:
a

array([[ 0,  0,  0, 10],
       [10, 10, 20, 20],
       [20, 30, 30, 30]])

In [25]:
np.array(a.flat)

array([ 0,  0,  0, 10, 10, 10, 20, 20, 20, 30, 30, 30])

In [26]:
a

array([[ 0,  0,  0, 10],
       [10, 10, 20, 20],
       [20, 30, 30, 30]])

In [85]:
b = a.ravel()
b

array([ 0,  0,  0, 10, 10, 10, 20, 20, 20, 30, 30, 30])

In [86]:
b[0] = 100

In [87]:
b

array([100,   0,   0,  10,  10,  10,  20,  20,  20,  30,  30,  30])

In [88]:
a

array([[100,   0,   0,  10],
       [ 10,  10,  20,  20],
       [ 20,  30,  30,  30]])

In [30]:
a.ravel(order = 'F')

array([ 0, 10, 20,  0, 10, 30,  0, 20, 30, 10, 20, 30])

In [89]:
b = a.flatten()
b[0] = 88
a

array([[100,   0,   0,  10],
       [ 10,  10,  20,  20],
       [ 20,  30,  30,  30]])

In [91]:
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [92]:
a.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [93]:
np.transpose(a)

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [94]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [95]:
a.shape

(3, 4)

In [97]:
a.shape = 4,3
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [36]:
a = np.arange(8).reshape(2,2,2)
a

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [37]:
np.rollaxis(a,2)

array([[[0, 2],
        [4, 6]],

       [[1, 3],
        [5, 7]]])

In [38]:
np.rollaxis(a, 2, 1)

array([[[0, 2],
        [1, 3]],

       [[4, 6],
        [5, 7]]])

In [39]:
a

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [40]:
np.rollaxis(a, 0)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [41]:
np.rollaxis(a, 1)

array([[[0, 1],
        [4, 5]],

       [[2, 3],
        [6, 7]]])

In [42]:
b = np.arange(6).reshape(2,3)
b

array([[0, 1, 2],
       [3, 4, 5]])

In [43]:
np.rollaxis(b, 0)

array([[0, 1, 2],
       [3, 4, 5]])

In [44]:
np.rollaxis(b, 1)

array([[0, 3],
       [1, 4],
       [2, 5]])

In [46]:
a = np.arange(8).reshape(2,2,2)
a

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [47]:
np.swapaxes(a, 2, 0)

array([[[0, 4],
        [2, 6]],

       [[1, 5],
        [3, 7]]])

In [61]:
a = np.arange(6).reshape(2,3)
b

array([[0, 1, 2],
       [3, 4, 5]])

In [62]:
np.swapaxes(a, 1, 0)

array([[0, 3],
       [1, 4],
       [2, 5]])

In [63]:
a

array([[0, 1, 2],
       [3, 4, 5]])

In [64]:
np.squeeze(a)

array([[0, 1, 2],
       [3, 4, 5]])

In [65]:
a.shape

(2, 3)

In [66]:
a.ndim

2

In [67]:
a.shape = 1, 2, 3

In [68]:
a.shape

(1, 2, 3)

In [70]:
a

array([[[0, 1, 2],
        [3, 4, 5]]])

In [71]:
np.squeeze(a)

array([[0, 1, 2],
       [3, 4, 5]])

In [74]:
a = np.array([1,2,3,4]).reshape(2,2)
a

array([[1, 2],
       [3, 4]])

In [76]:
b = np.array([5,6,7,8]).reshape(2,2)
b

array([[5, 6],
       [7, 8]])

### 1.6 连接数组

In [79]:
c = np.concatenate((a,b))
c

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [81]:
a.shape, b.shape, c.shape

((2, 2), (2, 2), (4, 2))

In [82]:
d = np.concatenate((a,b), axis = 1)
d

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [84]:
a = np.array([1,2,3,4]).reshape(2,2)
a

array([[1, 2],
       [3, 4]])

In [86]:
b = np.array([5,6,7,8]).reshape(2,2)
b

array([[5, 6],
       [7, 8]])

In [90]:
c = np.stack((a,b),0)
c

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [91]:
c.shape

(2, 2, 2)

In [92]:
d = np.stack((a,b),1)
d

array([[[1, 2],
        [5, 6]],

       [[3, 4],
        [7, 8]]])

In [93]:
d.shape

(2, 2, 2)

In [94]:
e = np.hstack((a,b))
e

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [95]:
e.shape

(2, 4)

In [97]:
a,b

(array([[1, 2],
        [3, 4]]), array([[5, 6],
        [7, 8]]))

In [96]:
f = np.vstack((a,b))
f

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

### 1.7 分割数组

In [111]:
a = np.arange(16).reshape(8,2)
a

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15]])

In [112]:
b = np.split(a, 2)
b

[array([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7]]), array([[ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]])]

In [113]:
b = np.split(a, 4)
b

[array([[0, 1],
        [2, 3]]), array([[4, 5],
        [6, 7]]), array([[ 8,  9],
        [10, 11]]), array([[12, 13],
        [14, 15]])]

In [114]:
a

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15]])

In [115]:
b

[array([[0, 1],
        [2, 3]]), array([[4, 5],
        [6, 7]]), array([[ 8,  9],
        [10, 11]]), array([[12, 13],
        [14, 15]])]

In [118]:
c = np.split(a, [3,5])
c

[array([[0, 1],
        [2, 3],
        [4, 5]]), array([[6, 7],
        [8, 9]]), array([[10, 11],
        [12, 13],
        [14, 15]])]

In [120]:
len(c)

3

### 1.8 Numpy位运算

In [20]:
a, b = 17, 15
bin(a), bin(b)

('0b10001', '0b1111')

In [21]:
anded = np.bitwise_and(a, b)
anded

1

In [22]:
bin(anded)

'0b1'

In [23]:
bin(np.bitwise_or(a, b))

'0b11111'

In [24]:
arr = np.array([a, b], dtype='u1')
arr

array([17, 15], dtype=uint8)

In [25]:
bin(a),bin(b)

('0b10001', '0b1111')

In [26]:
np.invert(arr)

array([238, 240], dtype=uint8)

In [27]:
bin(238),bin(240)

('0b11101110', '0b11110000')

In [28]:
arr = np.array([a, b], dtype='i1')
arr

array([17, 15], dtype=int8)

In [29]:
np.invert(arr)

array([-18, -16], dtype=int8)

In [30]:
bin(-18), bin(-16)

('-0b10010', '-0b10000')

In [31]:
np.left_shift(10,2)

40

In [32]:
np.binary_repr(10, width=8)

'00001010'

In [33]:
np.binary_repr(40, width=8)

'00101000'

In [35]:
np.right_shift(40, 1)

20

### 1.9 字符串函数

In [37]:
sa = np.array(['a','b','c','d']).reshape(2,2)
sa

array([['a', 'b'],
       ['c', 'd']], dtype='<U1')

In [38]:
sb = np.array(['A','B','C','D']).reshape(2,2)
sb

array([['A', 'B'],
       ['C', 'D']], dtype='<U1')

In [40]:
np.char.add(sa, sb)

array([['aA', 'bB'],
       ['cC', 'dD']], dtype='<U2')

In [41]:
np.char.multiply(sb, 3)

array([['AAA', 'BBB'],
       ['CCC', 'DDD']], dtype='<U3')

In [43]:
np.char.center(sb, 9, fillchar='*')

array([['****A****', '****B****'],
       ['****C****', '****D****']], dtype='<U9')

In [44]:
sc = np.char.multiply(sa, 6)
sc

array([['aaaaaa', 'bbbbbb'],
       ['cccccc', 'dddddd']], dtype='<U6')

In [45]:
np.char.capitalize(sc)

array([['Aaaaaa', 'Bbbbbb'],
       ['Cccccc', 'Dddddd']], dtype='<U6')

In [48]:
title = np.char.title('i like python')
title

array('I Like Python', dtype='<U13')

In [49]:
np.char.lower(title)

array('i like python', dtype='<U13')

In [50]:
np.char.upper(title)

array('I LIKE PYTHON', dtype='<U13')

In [51]:
np.char.split('a,b,c,d,e,f',',')

array(list(['a', 'b', 'c', 'd', 'e', 'f']), dtype=object)

### 1.10 算术函数

In [52]:
na = np.arange(12).reshape(3,4)
na

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [53]:
nb = np.arange(1,13).reshape(3,4)
nb

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [54]:
na * nb # na.multiply(nb)

array([[  0,   2,   6,  12],
       [ 20,  30,  42,  56],
       [ 72,  90, 110, 132]])

In [55]:
np.multiply(na, nb)

array([[  0,   2,   6,  12],
       [ 20,  30,  42,  56],
       [ 72,  90, 110, 132]])

In [56]:
na + nb

array([[ 1,  3,  5,  7],
       [ 9, 11, 13, 15],
       [17, 19, 21, 23]])

In [57]:
np.add(na, nb)

array([[ 1,  3,  5,  7],
       [ 9, 11, 13, 15],
       [17, 19, 21, 23]])

In [58]:
na - nb

array([[-1, -1, -1, -1],
       [-1, -1, -1, -1],
       [-1, -1, -1, -1]])

In [60]:
np.subtract(na, nb)

array([[-1, -1, -1, -1],
       [-1, -1, -1, -1],
       [-1, -1, -1, -1]])

In [61]:
na / nb

array([[0.        , 0.5       , 0.66666667, 0.75      ],
       [0.8       , 0.83333333, 0.85714286, 0.875     ],
       [0.88888889, 0.9       , 0.90909091, 0.91666667]])

In [62]:
np.round(na / nb, 2)

array([[0.  , 0.5 , 0.67, 0.75],
       [0.8 , 0.83, 0.86, 0.88],
       [0.89, 0.9 , 0.91, 0.92]])

In [69]:
nb.dtype

dtype('int64')

In [76]:
recip = np.reciprocal(nb.astype('f4'))
recip

array([[1.        , 0.5       , 0.33333334, 0.25      ],
       [0.2       , 0.16666667, 0.14285715, 0.125     ],
       [0.11111111, 0.1       , 0.09090909, 0.08333334]], dtype=float32)

In [77]:
np.round(recip, 2)

array([[1.  , 0.5 , 0.33, 0.25],
       [0.2 , 0.17, 0.14, 0.12],
       [0.11, 0.1 , 0.09, 0.08]], dtype=float32)

In [75]:
recip = 1 / nb
np.round(recip, 2)

array([[1.  , 0.5 , 0.33, 0.25],
       [0.2 , 0.17, 0.14, 0.12],
       [0.11, 0.1 , 0.09, 0.08]])

In [4]:
nums = np.arange(1,13).reshape(3,4)
nums

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [80]:
nums * 2

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [18, 20, 22, 24]])

In [81]:
2 * nums

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [18, 20, 22, 24]])

In [82]:
nums ** 2

array([[  1,   4,   9,  16],
       [ 25,  36,  49,  64],
       [ 81, 100, 121, 144]])

In [84]:
np.power(nums, 2)

array([[  1,   4,   9,  16],
       [ 25,  36,  49,  64],
       [ 81, 100, 121, 144]])

In [85]:
nb

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [86]:
nums / 2

array([[0.5, 1. , 1.5, 2. ],
       [2.5, 3. , 3.5, 4. ],
       [4.5, 5. , 5.5, 6. ]])

In [87]:
nums // 2

array([[0, 1, 1, 2],
       [2, 3, 3, 4],
       [4, 5, 5, 6]])

In [88]:
nums % 2

array([[1, 0, 1, 0],
       [1, 0, 1, 0],
       [1, 0, 1, 0]])

In [89]:
np.mod(nums, 2)

array([[1, 0, 1, 0],
       [1, 0, 1, 0],
       [1, 0, 1, 0]])

In [90]:
np.remainder(nums, 2)

array([[1, 0, 1, 0],
       [1, 0, 1, 0],
       [1, 0, 1, 0]])

In [92]:
nums % [2, 3, 4, 5]

array([[1, 2, 3, 4],
       [1, 0, 3, 3],
       [1, 1, 3, 2]])

In [93]:
np.mod(nums, np.arange(2, 6))

array([[1, 2, 3, 4],
       [1, 0, 3, 3],
       [1, 1, 3, 2]])

In [95]:
np.remainder(nums, np.arange(3,7))

array([[1, 2, 3, 4],
       [2, 2, 2, 2],
       [0, 2, 1, 0]])

### 1.11 Numpy统计函数

#### 最大/最小值

In [96]:
nums

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [5]:
np.amin(nums)

1

In [98]:
np.amin(nums, 0)

array([1, 2, 3, 4])

In [99]:
np.amin(nums, 1)

array([1, 5, 9])

In [100]:
np.amax(nums)

12

In [101]:
np.amax(nums, 0)

array([ 9, 10, 11, 12])

In [102]:
np.amax(nums, 1)

array([ 4,  8, 12])

#### 最大最小值差

In [103]:
np.ptp(nums)

11

In [104]:
np.ptp(nums, 0)

array([8, 8, 8, 8])

In [105]:
np.ptp(nums, 1)

array([3, 3, 3])

#### 百分位数

In [117]:
np.percentile(nums, 50)

6.5

In [112]:
nums

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [114]:
np.percentile(nums, 50, axis=0)

array([5., 6., 7., 8.])

In [115]:
np.percentile(nums, 50, axis=1)

array([ 2.5,  6.5, 10.5])

#### 中位数

In [116]:
np.median(nums)

6.5

In [7]:
nums.median()

AttributeError: 'numpy.ndarray' object has no attribute 'median'

In [118]:
np.median(nums, axis=0)

array([5., 6., 7., 8.])

In [119]:
np.median(nums, axis=1)

array([ 2.5,  6.5, 10.5])

#### 平均值

In [120]:
np.mean(nums)

6.5

In [121]:
np.mean(nums, axis=0)

array([5., 6., 7., 8.])

In [122]:
np.mean(nums, ax.flatis=1)

array([ 2.5,  6.5, 10.5])

In [123]:
np.average(nums)

6.5

In [124]:
np.average(nums, axis=0)

array([5., 6., 7., 8.])

In [125]:
np.average(nums, axis=1)

array([ 2.5,  6.5, 10.5])

In [126]:
np.average(nums, weights=nums)

8.333333333333334

In [129]:
np.sum(nums * nums) / np.sum(nums)

8.333333333333334

In [131]:
nums

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [133]:
np.average(nums, weights=[1,2,3], axis=0)

array([6.33333333, 7.33333333, 8.33333333, 9.33333333])

In [135]:
np.average(nums, weights=[1,2,3,4], axis=1)

array([ 3.,  7., 11.])

#### 标准差

In [136]:
np.std(nums)

3.452052529534663

In [159]:
np.std(nums, axis=0)

array([3.26598632, 3.26598632, 3.26598632, 3.26598632])

In [160]:
np.std(nums, axis=1)

array([1.11803399, 1.11803399, 1.11803399])

In [141]:
mean = np.mean(nums)
mean

6.5

In [143]:
diff = nums - mean
diff

array([[-5.5, -4.5, -3.5, -2.5],
       [-1.5, -0.5,  0.5,  1.5],
       [ 2.5,  3.5,  4.5,  5.5]])

In [148]:
variance = np.mean(diff**2)
variance

11.916666666666666

In [149]:
np.sqrt(variance)

3.452052529534663

#### 方差

In [152]:
var = np.mean((nums - np.mean(nums))**2)
var

11.916666666666666

In [153]:
np.var(nums)

11.916666666666666

In [161]:
var0 = np.var(nums, axis=0)
var0

array([10.66666667, 10.66666667, 10.66666667, 10.66666667])

In [163]:
var1 = np.var(nums, axis=1)
var1

array([1.25, 1.25, 1.25])

In [166]:
std0 = np.sqrt(var0)
std0

array([3.26598632, 3.26598632, 3.26598632, 3.26598632])

In [167]:
std1 = np.sqrt(var1)
std1

array([1.11803399, 1.11803399, 1.11803399])

#### 最大/最小元素索引

In [109]:
nums

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [105]:
np.argmax(nums)

11

In [106]:
nums.flatten()[11]

12

In [108]:
nums[2]

array([ 9, 10, 11, 12])

In [171]:
np.argmax(nums, axis=0)

array([2, 2, 2, 2])

In [172]:
np.argmax(nums, axis=1)

array([3, 3, 3])