# 数据重构
---

## 1. 使用Numpy

#### 加载数据

In [377]:
import numpy as np
!cat data/eg01.csv

#,A,B,C,D
1,A1,B1,C1,D1
2,A2,B2,C2,D2
3,A3,B3,C3,D3
4,A4,B4,C4,D4

In [378]:
# 加载数据
data = np.loadtxt('data/eg01.csv', comments=None,delimiter=',', dtype=str)
data

array([['#', 'A', 'B', 'C', 'D'],
       ['1', 'A1', 'B1', 'C1', 'D1'],
       ['2', 'A2', 'B2', 'C2', 'D2'],
       ['3', 'A3', 'B3', 'C3', 'D3'],
       ['4', 'A4', 'B4', 'C4', 'D4']], dtype='<U2')

### 1.1 数据选择

#### 选择行
##### （1）选择单行

In [379]:
# 选择首行
head= data[0]
head

array(['#', 'A', 'B', 'C', 'D'], dtype='<U2')

In [5]:
data[0,]

array(['A1', 'B1', 'C1', 'D1'], dtype='<U2')

In [6]:
data[0,:]

array(['A1', 'B1', 'C1', 'D1'], dtype='<U2')

In [7]:
data[0,...]

array(['A1', 'B1', 'C1', 'D1'], dtype='<U2')

In [8]:
# 选择尾行
tail = data[-1]
tail

array(['A4', 'B4', 'C4', 'D4'], dtype='<U2')

In [9]:
data[-1,]

array(['A4', 'B4', 'C4', 'D4'], dtype='<U2')

In [383]:
data[-1,:]

array(['4', 'A4', 'B4', 'C4', 'D4'], dtype='<U2')

In [381]:
data[:]

array([['#', 'A', 'B', 'C', 'D'],
       ['1', 'A1', 'B1', 'C1', 'D1'],
       ['2', 'A2', 'B2', 'C2', 'D2'],
       ['3', 'A3', 'B3', 'C3', 'D3'],
       ['4', 'A4', 'B4', 'C4', 'D4']], dtype='<U2')

In [11]:
data[-1,...]

array(['A4', 'B4', 'C4', 'D4'], dtype='<U2')

In [12]:
# 选择中间行
mid_index = len(data)//2
data[mid_index]

array(['A3', 'B3', 'C3', 'D3'], dtype='<U2')

In [380]:
data.size

25

In [13]:
data[mid_index,]

array(['A3', 'B3', 'C3', 'D3'], dtype='<U2')

In [14]:
data[mid_index,:]

array(['A3', 'B3', 'C3', 'D3'], dtype='<U2')

In [15]:
data[mid_index,...]

array(['A3', 'B3', 'C3', 'D3'], dtype='<U2')

##### （2）选择多行

1. 切片选择

In [16]:
# 选择前2行
data[:2]

array([['A1', 'B1', 'C1', 'D1'],
       ['A2', 'B2', 'C2', 'D2']], dtype='<U2')

In [17]:
data[:2,]

array([['A1', 'B1', 'C1', 'D1'],
       ['A2', 'B2', 'C2', 'D2']], dtype='<U2')

In [18]:
data[:2,:]

array([['A1', 'B1', 'C1', 'D1'],
       ['A2', 'B2', 'C2', 'D2']], dtype='<U2')

In [19]:
data[:2,...]

array([['A1', 'B1', 'C1', 'D1'],
       ['A2', 'B2', 'C2', 'D2']], dtype='<U2')

In [20]:
# 选择后2行
data[-2:]

array([['A3', 'B3', 'C3', 'D3'],
       ['A4', 'B4', 'C4', 'D4']], dtype='<U2')

In [21]:
data[-2:,]

array([['A3', 'B3', 'C3', 'D3'],
       ['A4', 'B4', 'C4', 'D4']], dtype='<U2')

In [22]:
data[-2:,...]

array([['A3', 'B3', 'C3', 'D3'],
       ['A4', 'B4', 'C4', 'D4']], dtype='<U2')

In [23]:
# 选择1～2行
data[1:3]

array([['A2', 'B2', 'C2', 'D2'],
       ['A3', 'B3', 'C3', 'D3']], dtype='<U2')

In [24]:
data[1:3,]

array([['A2', 'B2', 'C2', 'D2'],
       ['A3', 'B3', 'C3', 'D3']], dtype='<U2')

In [25]:
data[1:3,:]

array([['A2', 'B2', 'C2', 'D2'],
       ['A3', 'B3', 'C3', 'D3']], dtype='<U2')

In [26]:
data[1:3, ...]

array([['A2', 'B2', 'C2', 'D2'],
       ['A3', 'B3', 'C3', 'D3']], dtype='<U2')

In [27]:
# 奇数行
odd = slice(0,None,2)
data[odd]

array([['A1', 'B1', 'C1', 'D1'],
       ['A3', 'B3', 'C3', 'D3']], dtype='<U2')

In [28]:
data[odd,]

array([['A1', 'B1', 'C1', 'D1'],
       ['A3', 'B3', 'C3', 'D3']], dtype='<U2')

In [29]:
data[odd,:]

array([['A1', 'B1', 'C1', 'D1'],
       ['A3', 'B3', 'C3', 'D3']], dtype='<U2')

In [30]:
data[odd,...]

array([['A1', 'B1', 'C1', 'D1'],
       ['A3', 'B3', 'C3', 'D3']], dtype='<U2')

In [31]:
data[0:None:2]

array([['A1', 'B1', 'C1', 'D1'],
       ['A3', 'B3', 'C3', 'D3']], dtype='<U2')

In [32]:
data[0:None:2,]

array([['A1', 'B1', 'C1', 'D1'],
       ['A3', 'B3', 'C3', 'D3']], dtype='<U2')

In [33]:
data[0:None:2, :]

array([['A1', 'B1', 'C1', 'D1'],
       ['A3', 'B3', 'C3', 'D3']], dtype='<U2')

In [34]:
data[0:None:2, ...]

array([['A1', 'B1', 'C1', 'D1'],
       ['A3', 'B3', 'C3', 'D3']], dtype='<U2')

In [35]:
# 偶数行
even = slice(1, None, 2)
data[even]

array([['A2', 'B2', 'C2', 'D2'],
       ['A4', 'B4', 'C4', 'D4']], dtype='<U2')

In [36]:
data[even,]

array([['A2', 'B2', 'C2', 'D2'],
       ['A4', 'B4', 'C4', 'D4']], dtype='<U2')

In [37]:
data[even,:]

array([['A2', 'B2', 'C2', 'D2'],
       ['A4', 'B4', 'C4', 'D4']], dtype='<U2')

In [38]:
data[even, ...]

array([['A2', 'B2', 'C2', 'D2'],
       ['A4', 'B4', 'C4', 'D4']], dtype='<U2')

In [39]:
data[1:None:2]

array([['A2', 'B2', 'C2', 'D2'],
       ['A4', 'B4', 'C4', 'D4']], dtype='<U2')

In [40]:
data[1:None:2,]

array([['A2', 'B2', 'C2', 'D2'],
       ['A4', 'B4', 'C4', 'D4']], dtype='<U2')

In [41]:
data[1:None:2, :]

array([['A2', 'B2', 'C2', 'D2'],
       ['A4', 'B4', 'C4', 'D4']], dtype='<U2')

In [42]:
data[1:None:2, ...]

array([['A2', 'B2', 'C2', 'D2'],
       ['A4', 'B4', 'C4', 'D4']], dtype='<U2')

In [43]:
# 逆序选择
data[::-1]

array([['A4', 'B4', 'C4', 'D4'],
       ['A3', 'B3', 'C3', 'D3'],
       ['A2', 'B2', 'C2', 'D2'],
       ['A1', 'B1', 'C1', 'D1']], dtype='<U2')

In [44]:
data[::-1,]

array([['A4', 'B4', 'C4', 'D4'],
       ['A3', 'B3', 'C3', 'D3'],
       ['A2', 'B2', 'C2', 'D2'],
       ['A1', 'B1', 'C1', 'D1']], dtype='<U2')

In [45]:
data[::-1,:] #[from: to: step]

array([['A4', 'B4', 'C4', 'D4'],
       ['A3', 'B3', 'C3', 'D3'],
       ['A2', 'B2', 'C2', 'D2'],
       ['A1', 'B1', 'C1', 'D1']], dtype='<U2')

In [46]:
data[::-1,...]

array([['A4', 'B4', 'C4', 'D4'],
       ['A3', 'B3', 'C3', 'D3'],
       ['A2', 'B2', 'C2', 'D2'],
       ['A1', 'B1', 'C1', 'D1']], dtype='<U2')

2. 使用索引数组选择

In [62]:
# 使用索引数组选择0，2，3行
row_indices = [1, 2, 4]
data[row_indices]

array([['1', 'A1', 'B1', 'C1', 'D1'],
       ['2', 'A2', 'B2', 'C2', 'D2'],
       ['4', 'A4', 'B4', 'C4', 'D4']], dtype='<U2')

In [384]:
data[[1,3,4]]

array([['1', 'A1', 'B1', 'C1', 'D1'],
       ['3', 'A3', 'B3', 'C3', 'D3'],
       ['4', 'A4', 'B4', 'C4', 'D4']], dtype='<U2')

In [63]:
row_indices = [2, 1, 4, 3]
data[row_indices]

array([['2', 'A2', 'B2', 'C2', 'D2'],
       ['1', 'A1', 'B1', 'C1', 'D1'],
       ['4', 'A4', 'B4', 'C4', 'D4'],
       ['3', 'A3', 'B3', 'C3', 'D3']], dtype='<U2')

In [65]:
row_indices = [2, 1, 4, 3]
col_indices = [2, 4, 3, 1]
data[row_indices, col_indices] # [2,2],[1,4],[4,3],[3,1]

array(['B2', 'D1', 'C4', 'A3'], dtype='<U2')

In [66]:
data[np.ix_(row_indices, col_indices)]

array([['B2', 'D2', 'C2', 'A2'],
       ['B1', 'D1', 'C1', 'A1'],
       ['B4', 'D4', 'C4', 'A4'],
       ['B3', 'D3', 'C3', 'A3']], dtype='<U2')

In [67]:
data[row_indices,]

array([['2', 'A2', 'B2', 'C2', 'D2'],
       ['1', 'A1', 'B1', 'C1', 'D1'],
       ['4', 'A4', 'B4', 'C4', 'D4'],
       ['3', 'A3', 'B3', 'C3', 'D3']], dtype='<U2')

In [68]:
data[row_indices,:]

array([['2', 'A2', 'B2', 'C2', 'D2'],
       ['1', 'A1', 'B1', 'C1', 'D1'],
       ['4', 'A4', 'B4', 'C4', 'D4'],
       ['3', 'A3', 'B3', 'C3', 'D3']], dtype='<U2')

In [69]:
data[row_indices, ...]

array([['2', 'A2', 'B2', 'C2', 'D2'],
       ['1', 'A1', 'B1', 'C1', 'D1'],
       ['4', 'A4', 'B4', 'C4', 'D4'],
       ['3', 'A3', 'B3', 'C3', 'D3']], dtype='<U2')

3. 使用布尔数组选择

In [72]:
# 手动创建布尔数组
selected_rows = np.array([False, True, False, False, True])
selected_rows

array([False,  True, False, False,  True])

In [73]:
data[selected_rows]

array([['1', 'A1', 'B1', 'C1', 'D1'],
       ['4', 'A4', 'B4', 'C4', 'D4']], dtype='<U2')

In [74]:
# 根据条件创建布尔数组
selected_rows = data[:,0] > '2'
selected_rows

array([False, False, False,  True,  True])

In [385]:
'A' < 'a'

True

In [386]:
'A' < '1'

False

In [75]:
selected_rows = data[...,0] > '2'
selected_rows

array([False, False, False,  True,  True])

In [76]:
data[selected_rows]

array([['3', 'A3', 'B3', 'C3', 'D3'],
       ['4', 'A4', 'B4', 'C4', 'D4']], dtype='<U2')

In [388]:
# 选择第一列元素为‘A'的行
selected_rows = data[:,1] == 'A' 
data[selected_rows]

array([['#', 'A', 'B', 'C', 'D']], dtype='<U2')

In [389]:
selected_rows = data[...,1] == 'A' 
data[selected_rows]

array([['#', 'A', 'B', 'C', 'D']], dtype='<U2')

In [390]:
# 反选
data[~selected_rows]

array([['1', 'A1', 'B1', 'C1', 'D1'],
       ['2', 'A2', 'B2', 'C2', 'D2'],
       ['3', 'A3', 'B3', 'C3', 'D3'],
       ['4', 'A4', 'B4', 'C4', 'D4']], dtype='<U2')

In [84]:
# 选择第二列元素以字符串B开始的行
selected_rows = np.char.startswith(data[:,2],'B')
selected_rows

array([ True,  True,  True,  True,  True])

In [85]:
data[selected_rows]

array([['#', 'A', 'B', 'C', 'D'],
       ['1', 'A1', 'B1', 'C1', 'D1'],
       ['2', 'A2', 'B2', 'C2', 'D2'],
       ['3', 'A3', 'B3', 'C3', 'D3'],
       ['4', 'A4', 'B4', 'C4', 'D4']], dtype='<U2')

In [87]:
selected_rows = np.char.startswith(data[...,2],'B')
selected_rows

array([ True,  True,  True,  True,  True])

In [88]:
data[selected_rows]

array([['#', 'A', 'B', 'C', 'D'],
       ['1', 'A1', 'B1', 'C1', 'D1'],
       ['2', 'A2', 'B2', 'C2', 'D2'],
       ['3', 'A3', 'B3', 'C3', 'D3'],
       ['4', 'A4', 'B4', 'C4', 'D4']], dtype='<U2')

4. 使用where查询

In [89]:
selected_rows = np.where(data[:,0] == '4')
selected_rows

(array([4]),)

In [90]:
data[selected_rows]

array([['4', 'A4', 'B4', 'C4', 'D4']], dtype='<U2')

In [160]:
selected_elems = np.where(data > 'C')
selected_elems

(array([0, 1, 1, 2, 2, 3, 3, 4, 4]), array([4, 3, 4, 3, 4, 3, 4, 3, 4]))

In [161]:
data[selected_elems]

array(['D', 'C1', 'D1', 'C2', 'D2', 'C3', 'D3', 'C4', 'D4'], dtype='<U2')

In [165]:
np.extract(data > 'C', data)

array(['D', 'C1', 'D1', 'C2', 'D2', 'C3', 'D3', 'C4', 'D4'], dtype='<U2')

In [394]:
help(np.where)

Help on built-in function where in module numpy:

where(...)
    where(condition, [x, y])
    
    Return elements chosen from `x` or `y` depending on `condition`.
    
    .. note::
        When only `condition` is provided, this function is a shorthand for
        ``np.asarray(condition).nonzero()``. Using `nonzero` directly should be
        preferred, as it behaves correctly for subclasses. The rest of this
        documentation covers only the case where all three arguments are
        provided.
    
    Parameters
    ----------
    condition : array_like, bool
        Where True, yield `x`, otherwise yield `y`.
    x, y : array_like
        Values from which to choose. `x`, `y` and `condition` need to be
        broadcastable to some shape.
    
    Returns
    -------
    out : ndarray
        An array with elements from `x` where `condition` is True, and elements
        from `y` elsewhere.
    
    See Also
    --------
    choose
    nonzero : The function that is called whe

#### 选择列

##### （1）选择单列

In [166]:
data[:,0] # 第一列

array(['#', '1', '2', '3', '4'], dtype='<U2')

In [396]:
data[1,]

array(['1', 'A1', 'B1', 'C1', 'D1'], dtype='<U2')

In [167]:
data[...,0]

array(['#', '1', '2', '3', '4'], dtype='<U2')

In [168]:
data[:,-1] # 最后一列

array(['D', 'D1', 'D2', 'D3', 'D4'], dtype='<U2')

In [169]:
data[..., -1]

array(['D', 'D1', 'D2', 'D3', 'D4'], dtype='<U2')

In [170]:
data[:, data.shape[1]//2] # 中间列

array(['B', 'B1', 'B2', 'B3', 'B4'], dtype='<U2')

In [171]:
data[...,1] # 指定列

array(['A', 'A1', 'A2', 'A3', 'A4'], dtype='<U2')

##### （2）选择多列

1. 切片选择

In [172]:
data[:, :2] # 前2列

array([['#', 'A'],
       ['1', 'A1'],
       ['2', 'A2'],
       ['3', 'A3'],
       ['4', 'A4']], dtype='<U2')

In [173]:
data[..., :2]

array([['#', 'A'],
       ['1', 'A1'],
       ['2', 'A2'],
       ['3', 'A3'],
       ['4', 'A4']], dtype='<U2')

In [397]:
data[:, -2:] # 后2列

array([['C', 'D'],
       ['C1', 'D1'],
       ['C2', 'D2'],
       ['C3', 'D3'],
       ['C4', 'D4']], dtype='<U2')

In [175]:
data[:, 0:None:2] # 偶数列

array([['#', 'B', 'D'],
       ['1', 'B1', 'D1'],
       ['2', 'B2', 'D2'],
       ['3', 'B3', 'D3'],
       ['4', 'B4', 'D4']], dtype='<U2')

In [176]:
data[:, 1:None:2] # 奇数列

array([['A', 'C'],
       ['A1', 'C1'],
       ['A2', 'C2'],
       ['A3', 'C3'],
       ['A4', 'C4']], dtype='<U2')

In [177]:
data[:, slice(1,None,2)]

array([['A', 'C'],
       ['A1', 'C1'],
       ['A2', 'C2'],
       ['A3', 'C3'],
       ['A4', 'C4']], dtype='<U2')

In [178]:
data[:,::-1] # 列逆序

array([['D', 'C', 'B', 'A', '#'],
       ['D1', 'C1', 'B1', 'A1', '1'],
       ['D2', 'C2', 'B2', 'A2', '2'],
       ['D3', 'C3', 'B3', 'A3', '3'],
       ['D4', 'C4', 'B4', 'A4', '4']], dtype='<U2')

In [179]:
data[::-1, ::-1] # 行列逆序

array([['D4', 'C4', 'B4', 'A4', '4'],
       ['D3', 'C3', 'B3', 'A3', '3'],
       ['D2', 'C2', 'B2', 'A2', '2'],
       ['D1', 'C1', 'B1', 'A1', '1'],
       ['D', 'C', 'B', 'A', '#']], dtype='<U2')

2. 索引数组选择

In [180]:
data[:, [0,2]] # 使用索引数组选择0，2列

array([['#', 'B'],
       ['1', 'B1'],
       ['2', 'B2'],
       ['3', 'B3'],
       ['4', 'B4']], dtype='<U2')

In [181]:
data[:, [1,3]]

array([['A', 'C'],
       ['A1', 'C1'],
       ['A2', 'C2'],
       ['A3', 'C3'],
       ['A4', 'C4']], dtype='<U2')

In [182]:
data[:,[2,3,0,1]]

array([['B', 'C', '#', 'A'],
       ['B1', 'C1', '1', 'A1'],
       ['B2', 'C2', '2', 'A2'],
       ['B3', 'C3', '3', 'A3'],
       ['B4', 'C4', '4', 'A4']], dtype='<U2')

In [183]:
data[[3,4,1,2],[2,3,0,1]]

array(['B3', 'C4', '1', 'A2'], dtype='<U2')

In [184]:
indices = np.ix_([3,4,1,2],[2,3,0,1])
indices

(array([[3],
        [4],
        [1],
        [2]]), array([[2, 3, 0, 1]]))

In [185]:
data[indices]

array([['B3', 'C3', '3', 'A3'],
       ['B4', 'C4', '4', 'A4'],
       ['B1', 'C1', '1', 'A1'],
       ['B2', 'C2', '2', 'A2']], dtype='<U2')

3. 使用布尔数组选择列

In [186]:
selected_cols = [False, True, False, False, True] # 指定要选择的列
data[:, selected_cols]

array([['A', 'D'],
       ['A1', 'D1'],
       ['A2', 'D2'],
       ['A3', 'D3'],
       ['A4', 'D4']], dtype='<U2')

In [400]:
selected_cols = data[2,:] == '2'
selected_cols

array([ True, False, False, False, False])

In [403]:
data[:,selected_cols]

array([['#'],
       ['1'],
       ['2'],
       ['3'],
       ['4']], dtype='<U2')

In [188]:
data[:, selected_cols]

array([['#'],
       ['1'],
       ['2'],
       ['3'],
       ['4']], dtype='<U2')

In [405]:
selected_cols = np.char.startswith(data, 'B')
selected_cols

array([[False, False,  True, False, False],
       [False, False,  True, False, False],
       [False, False,  True, False, False],
       [False, False,  True, False, False],
       [False, False,  True, False, False]])

In [406]:
data[selected_cols]

array(['B', 'B1', 'B2', 'B3', 'B4'], dtype='<U2')

In [407]:
selected_cols = np.all(selected_cols, axis=0)
selected_cols

array([False, False,  True, False, False])

In [190]:
data[:, selected_cols]

array([['B'],
       ['B1'],
       ['B2'],
       ['B3'],
       ['B4']], dtype='<U2')

#### 选择行与列

In [409]:
selected_rows = [2, 4]
selected_cols = [1, 3]

In [412]:
data[selected_rows, selected_cols]

array(['A2', 'C4'], dtype='<U2')

In [410]:
np.ix_(selected_rows, selected_cols)

(array([[2],
        [4]]), array([[1, 3]]))

In [411]:
data[np.ix_(selected_rows, selected_cols)]

array([['A2', 'C2'],
       ['A4', 'C4']], dtype='<U2')

In [192]:
data[1:4, 1:3] # 中间区域

array([['A1', 'B1'],
       ['A2', 'B2'],
       ['A3', 'B3']], dtype='<U2')

### 1.2 数据拆分

#### 按行拆分

In [415]:
splited_rows = np.split(data[1:], 2) # 2等分
splited_rows

[array([['1', 'A1', 'B1', 'C1', 'D1'],
        ['2', 'A2', 'B2', 'C2', 'D2']], dtype='<U2'),
 array([['3', 'A3', 'B3', 'C3', 'D3'],
        ['4', 'A4', 'B4', 'C4', 'D4']], dtype='<U2')]

In [194]:
splited_rows[1]

array([['3', 'A3', 'B3', 'C3', 'D3'],
       ['4', 'A4', 'B4', 'C4', 'D4']], dtype='<U2')

In [195]:
splited_rows = np.array_split(data, 2) # 分成2个子数组
splited_rows[0]

array([['#', 'A', 'B', 'C', 'D'],
       ['1', 'A1', 'B1', 'C1', 'D1'],
       ['2', 'A2', 'B2', 'C2', 'D2']], dtype='<U2')

In [196]:
splited_rows[1]

array([['3', 'A3', 'B3', 'C3', 'D3'],
       ['4', 'A4', 'B4', 'C4', 'D4']], dtype='<U2')

In [197]:
splited_rows = np.split(data, [2, 4]) # 按行索引拆分
for rows in splited_rows:
    print(rows)
    print('-' * 28)

[['#' 'A' 'B' 'C' 'D']
 ['1' 'A1' 'B1' 'C1' 'D1']]
----------------------------
[['2' 'A2' 'B2' 'C2' 'D2']
 ['3' 'A3' 'B3' 'C3' 'D3']]
----------------------------
[['4' 'A4' 'B4' 'C4' 'D4']]
----------------------------


In [198]:
splited_rows = np.vsplit(data, [3])
for rows in splited_rows:
    print(rows)
    print('-' * 26)

[['#' 'A' 'B' 'C' 'D']
 ['1' 'A1' 'B1' 'C1' 'D1']
 ['2' 'A2' 'B2' 'C2' 'D2']]
--------------------------
[['3' 'A3' 'B3' 'C3' 'D3']
 ['4' 'A4' 'B4' 'C4' 'D4']]
--------------------------


#### 按列拆分

In [199]:
splited_cols = np.split(data[:,1:], 2, axis=1) # 2等分
for cols in splited_cols:
    print(cols)
    print('-' * 12)

[['A' 'B']
 ['A1' 'B1']
 ['A2' 'B2']
 ['A3' 'B3']
 ['A4' 'B4']]
------------
[['C' 'D']
 ['C1' 'D1']
 ['C2' 'D2']
 ['C3' 'D3']
 ['C4' 'D4']]
------------


In [200]:
splited_cols = np.array_split(data, 3, axis=1) # 分成3分
for cols in splited_cols:
    print(cols)
    print('-' * 12)

[['#' 'A']
 ['1' 'A1']
 ['2' 'A2']
 ['3' 'A3']
 ['4' 'A4']]
------------
[['B' 'C']
 ['B1' 'C1']
 ['B2' 'C2']
 ['B3' 'C3']
 ['B4' 'C4']]
------------
[['D']
 ['D1']
 ['D2']
 ['D3']
 ['D4']]
------------


In [201]:
splited_cols = np.split(data, [2,4], axis=1) # 按列索引拆分
for cols in splited_cols:
    print(cols)
    print('-' * 12)

[['#' 'A']
 ['1' 'A1']
 ['2' 'A2']
 ['3' 'A3']
 ['4' 'A4']]
------------
[['B' 'C']
 ['B1' 'C1']
 ['B2' 'C2']
 ['B3' 'C3']
 ['B4' 'C4']]
------------
[['D']
 ['D1']
 ['D2']
 ['D3']
 ['D4']]
------------


In [202]:
splited_cols = np.hsplit(data[:,1:], 2)
for cols in splited_cols:
    print(cols)
    print('-' * 12)

[['A' 'B']
 ['A1' 'B1']
 ['A2' 'B2']
 ['A3' 'B3']
 ['A4' 'B4']]
------------
[['C' 'D']
 ['C1' 'D1']
 ['C2' 'D2']
 ['C3' 'D3']
 ['C4' 'D4']]
------------


### 1.3 数据拼接

#### 按行拼接

In [417]:
rows_up, rows_down = np.vsplit(data, [3])
rows_up

array([['#', 'A', 'B', 'C', 'D'],
       ['1', 'A1', 'B1', 'C1', 'D1'],
       ['2', 'A2', 'B2', 'C2', 'D2']], dtype='<U2')

In [418]:
rows_down

array([['3', 'A3', 'B3', 'C3', 'D3'],
       ['4', 'A4', 'B4', 'C4', 'D4']], dtype='<U2')

In [205]:
# 使用numpy.concatenate方法连接
concat_rows = np.concatenate((rows_up, rows_down))
concat_rows

array([['#', 'A', 'B', 'C', 'D'],
       ['1', 'A1', 'B1', 'C1', 'D1'],
       ['2', 'A2', 'B2', 'C2', 'D2'],
       ['3', 'A3', 'B3', 'C3', 'D3'],
       ['4', 'A4', 'B4', 'C4', 'D4']], dtype='<U2')

In [421]:
help(np.concatenate)

Help on built-in function concatenate in module numpy:

concatenate(...)
    concatenate((a1, a2, ...), axis=0, out=None)
    
    Join a sequence of arrays along an existing axis.
    
    Parameters
    ----------
    a1, a2, ... : sequence of array_like
        The arrays must have the same shape, except in the dimension
        corresponding to `axis` (the first, by default).
    axis : int, optional
        The axis along which the arrays will be joined.  If axis is None,
        arrays are flattened before use.  Default is 0.
    out : ndarray, optional
        If provided, the destination to place the result. The shape must be
        correct, matching that of what concatenate would have returned if no
        out argument were specified.
    
    Returns
    -------
    res : ndarray
        The concatenated array.
    
    See Also
    --------
    ma.concatenate : Concatenate function that preserves input masks.
    array_split : Split an array into multiple sub-arrays of equ

In [206]:
# 使用numpy.append方法沿0轴（垂直方向）追加
appended = np.append(rows_up, rows_down, axis=0)
appended

array([['#', 'A', 'B', 'C', 'D'],
       ['1', 'A1', 'B1', 'C1', 'D1'],
       ['2', 'A2', 'B2', 'C2', 'D2'],
       ['3', 'A3', 'B3', 'C3', 'D3'],
       ['4', 'A4', 'B4', 'C4', 'D4']], dtype='<U2')

In [207]:
# 使用numpy.insert方法
inserted = np.insert(rows_up, len(rows_up), rows_down, axis=0)
inserted

array([['#', 'A', 'B', 'C', 'D'],
       ['1', 'A1', 'B1', 'C1', 'D1'],
       ['2', 'A2', 'B2', 'C2', 'D2'],
       ['3', 'A3', 'B3', 'C3', 'D3'],
       ['4', 'A4', 'B4', 'C4', 'D4']], dtype='<U2')

In [208]:
# 使用numpy.vstack方法
vstacked = np.vstack((rows_up, rows_down))
vstacked

array([['#', 'A', 'B', 'C', 'D'],
       ['1', 'A1', 'B1', 'C1', 'D1'],
       ['2', 'A2', 'B2', 'C2', 'D2'],
       ['3', 'A3', 'B3', 'C3', 'D3'],
       ['4', 'A4', 'B4', 'C4', 'D4']], dtype='<U2')

#### 按列拼接

In [425]:
cols_left, cols_right = np.hsplit(data, [3])
cols_left

array([['#', 'A', 'B'],
       ['1', 'A1', 'B1'],
       ['2', 'A2', 'B2'],
       ['3', 'A3', 'B3'],
       ['4', 'A4', 'B4']], dtype='<U2')

In [426]:
cols_right

array([['C', 'D'],
       ['C1', 'D1'],
       ['C2', 'D2'],
       ['C3', 'D3'],
       ['C4', 'D4']], dtype='<U2')

In [427]:
# 使用numpy.concatenate方法沿1轴（水平方向）连接
concat_cols = np.concatenate((cols_left, cols_right), axis=1)
concat_cols

array([['#', 'A', 'B', 'C', 'D'],
       ['1', 'A1', 'B1', 'C1', 'D1'],
       ['2', 'A2', 'B2', 'C2', 'D2'],
       ['3', 'A3', 'B3', 'C3', 'D3'],
       ['4', 'A4', 'B4', 'C4', 'D4']], dtype='<U2')

In [428]:
# 沿1轴(水平方向）追加
appended = np.append(cols_left, cols_right, axis=1)
appended

array([['#', 'A', 'B', 'C', 'D'],
       ['1', 'A1', 'B1', 'C1', 'D1'],
       ['2', 'A2', 'B2', 'C2', 'D2'],
       ['3', 'A3', 'B3', 'C3', 'D3'],
       ['4', 'A4', 'B4', 'C4', 'D4']], dtype='<U2')

In [429]:
cols_left

array([['#', 'A', 'B'],
       ['1', 'A1', 'B1'],
       ['2', 'A2', 'B2'],
       ['3', 'A3', 'B3'],
       ['4', 'A4', 'B4']], dtype='<U2')

In [430]:
cols_left.shape

(5, 3)

In [215]:
cols_right

array([['C', 'D'],
       ['C1', 'D1'],
       ['C2', 'D2'],
       ['C3', 'D3'],
       ['C4', 'D4']], dtype='<U2')

In [433]:
cols_right.T

array([['C', 'C1', 'C2', 'C3', 'C4'],
       ['D', 'D1', 'D2', 'D3', 'D4']], dtype='<U2')

In [435]:
# 沿1轴（水平方向）插入(被插入的数组需要转置)
inserted = np.insert(cols_left, cols_left.shape[1], cols_right.T, axis=1)
inserted

array([['#', 'A', 'B', 'C', 'D'],
       ['1', 'A1', 'B1', 'C1', 'D1'],
       ['2', 'A2', 'B2', 'C2', 'D2'],
       ['3', 'A3', 'B3', 'C3', 'D3'],
       ['4', 'A4', 'B4', 'C4', 'D4']], dtype='<U2')

In [218]:
# 沿水平方向堆叠
hstacked = np.hstack((cols_left, cols_right))
hstacked

array([['#', 'A', 'B', 'C', 'D'],
       ['1', 'A1', 'B1', 'C1', 'D1'],
       ['2', 'A2', 'B2', 'C2', 'D2'],
       ['3', 'A3', 'B3', 'C3', 'D3'],
       ['4', 'A4', 'B4', 'C4', 'D4']], dtype='<U2')

In [219]:
# 按列堆叠
cols_stacked = np.column_stack((cols_left, cols_right))
cols_stacked

array([['#', 'A', 'B', 'C', 'D'],
       ['1', 'A1', 'B1', 'C1', 'D1'],
       ['2', 'A2', 'B2', 'C2', 'D2'],
       ['3', 'A3', 'B3', 'C3', 'D3'],
       ['4', 'A4', 'B4', 'C4', 'D4']], dtype='<U2')

In [436]:
!ls -l

total 9264
-rw-r--r--   1 xiaobai  staff    31435  8 11 16:40 Docker_Hadoop_Cluster.ipynb
-rw-r--r--   1 xiaobai  staff     5944  8 14 23:01 bigdata_analysis_exam.ipynb
-rw-r--r--   1 xiaobai  staff   895558  8 12 20:07 ch01.ipynb
-rw-r--r--   1 xiaobai  staff    44031  8 13 10:34 ch02.ipynb
-rw-r--r--   1 xiaobai  staff   105199  8 13 20:32 ch03.ipynb
-rw-r--r--   1 xiaobai  staff    42941  8 14 21:01 ch04.ipynb
-rw-r--r--   1 xiaobai  staff    54662  8 14 21:35 ch05.ipynb
-rw-r--r--   1 xiaobai  staff    35649  8 25 21:06 ch06.ipynb
drwxr-xr-x   4 xiaobai  staff      128  8 11 20:20 conf
drwxr-xr-x  40 xiaobai  staff     1280  9  4 22:25 data
-rw-r--r--   1 xiaobai  staff   335233  9  5 11:34 day03_data_reconstruction.ipynb
-rw-r--r--   1 xiaobai  staff     2873  9  4 23:03 day03_exercise.ipynb
-rw-r--r--   1 xiaobai  staff  3020812  9  1 09:10 day04_statistic_analysis.ipynb
drwxr-xr-x   6 xiaobai  staff      192  8 13 08:18 docker
-rw-r--r--@  1 xiaobai  staff     3590  8 13 10:51 d

## 2. 使用Pandas

### 加载数据

In [3]:
import pandas as pd

In [4]:
!cat data/eg01.csv

#,A,B,C,D
1,A1,B1,C1,D1
2,A2,B2,C2,D2
3,A3,B3,C3,D3
4,A4,B4,C4,D4

In [5]:
df = pd.read_csv('data/eg01.csv')
df

#   A   B   C   D
0  1  A1  B1  C1  D1
1  2  A2  B2  C2  D2
2  3  A3  B3  C3  D3
3  4  A4  B4  C4  D4

### 2.1 数据选择

#### 选择行

##### （1）选择单行

In [6]:
df.iloc[0] # 首行，基于位置

#     1
A    A1
B    B1
C    C1
D    D1
Name: 0, dtype: object

In [438]:
df['A']

0    A1
1    A2
2    A3
3    A4
Name: A, dtype: object

In [7]:
df.iloc[-1] # 尾行

#     4
A    A4
B    B4
C    C4
D    D4
Name: 3, dtype: object

In [8]:
df.iloc[len(df) // 2] # 中间行

#     3
A    A3
B    B3
C    C3
D    D3
Name: 2, dtype: object

In [439]:
df.loc[0] # 基于

#     1
A    A1
B    B1
C    C1
D    D1
Name: 0, dtype: object

In [10]:
list(df.index)

[0, 1, 2, 3]

In [444]:
df.loc[1,:]

#     2
A    A2
B    B2
C    C2
D    D2
Name: 1, dtype: object

In [446]:
df2 = df.set_index('#')
df2

A   B   C   D
#                
1  A1  B1  C1  D1
2  A2  B2  C2  D2
3  A3  B3  C3  D3
4  A4  B4  C4  D4

In [447]:
df2.index

Int64Index([1, 2, 3, 4], dtype='int64', name='#')

In [448]:
df2.loc[1]

A    A1
B    B1
C    C1
D    D1
Name: 1, dtype: object

In [449]:
df2.iloc[1]

A    A2
B    B2
C    C2
D    D2
Name: 2, dtype: object

In [15]:
df3 = df2.reset_index().set_index('A')
df3

#   B   C   D
A                
A1  1  B1  C1  D1
A2  2  B2  C2  D2
A3  3  B3  C3  D3
A4  4  B4  C4  D4

In [458]:
df3.iloc[0]

#     1
B    B1
C    C1
D    D1
Name: A1, dtype: object

In [16]:
df3.index

Index(['A1', 'A2', 'A3', 'A4'], dtype='object', name='A')

In [461]:
df3.loc['A2']

#     2
B    B2
C    C2
D    D2
Name: A2, dtype: object

##### （2）选择多行

1. 使用切片选择

In [18]:
df.head(2)

#   A   B   C   D
0  1  A1  B1  C1  D1
1  2  A2  B2  C2  D2

In [452]:
df[:2]

#   A   B   C   D
0  1  A1  B1  C1  D1
1  2  A2  B2  C2  D2

In [454]:
df['#']

0    1
1    2
2    3
3    4
Name: #, dtype: int64

In [20]:
df.iloc[:2]

#   A   B   C   D
0  1  A1  B1  C1  D1
1  2  A2  B2  C2  D2

In [455]:
df.iloc[2]

#     3
A    A3
B    B3
C    C3
D    D3
Name: 2, dtype: object

In [456]:
df.loc[2]

#     3
A    A3
B    B3
C    C3
D    D3
Name: 2, dtype: object

In [21]:
df.loc[:2]

#   A   B   C   D
0  1  A1  B1  C1  D1
1  2  A2  B2  C2  D2
2  3  A3  B3  C3  D3

In [22]:
df.tail(2)

#   A   B   C   D
2  3  A3  B3  C3  D3
3  4  A4  B4  C4  D4

In [23]:
df[2:]

#   A   B   C   D
2  3  A3  B3  C3  D3
3  4  A4  B4  C4  D4

In [24]:
df.iloc[:2]

#   A   B   C   D
0  1  A1  B1  C1  D1
1  2  A2  B2  C2  D2

In [25]:
df.loc[:2]

#   A   B   C   D
0  1  A1  B1  C1  D1
1  2  A2  B2  C2  D2
2  3  A3  B3  C3  D3

In [26]:
df[1:3]

#   A   B   C   D
1  2  A2  B2  C2  D2
2  3  A3  B3  C3  D3

In [27]:
df.iloc[1:3]

#   A   B   C   D
1  2  A2  B2  C2  D2
2  3  A3  B3  C3  D3

In [28]:
df.loc[1:3]

#   A   B   C   D
1  2  A2  B2  C2  D2
2  3  A3  B3  C3  D3
3  4  A4  B4  C4  D4

In [29]:
list(df.index)

[0, 1, 2, 3]

In [30]:
df2 = df.set_index('#')
df2

A   B   C   D
#                
1  A1  B1  C1  D1
2  A2  B2  C2  D2
3  A3  B3  C3  D3
4  A4  B4  C4  D4

In [31]:
df2.index

Int64Index([1, 2, 3, 4], dtype='int64', name='#')

In [32]:
df2[1:3]

A   B   C   D
#                
2  A2  B2  C2  D2
3  A3  B3  C3  D3

In [33]:
df3 = df.set_index('A')
df3

#   B   C   D
A                
A1  1  B1  C1  D1
A2  2  B2  C2  D2
A3  3  B3  C3  D3
A4  4  B4  C4  D4

In [34]:
df3.loc['A2':'A4']

#   B   C   D
A                
A2  2  B2  C2  D2
A3  3  B3  C3  D3
A4  4  B4  C4  D4

In [35]:
df3.iloc[2:4]

#   B   C   D
A                
A3  3  B3  C3  D3
A4  4  B4  C4  D4

In [36]:
df3.iloc[::-1] # 逆序

#   B   C   D
A                
A4  4  B4  C4  D4
A3  3  B3  C3  D3
A2  2  B2  C2  D2
A1  1  B1  C1  D1

In [37]:
df3.iloc[::2,:]

#   B   C   D
A                
A1  1  B1  C1  D1
A3  3  B3  C3  D3

In [38]:
df3.iloc[1::2]

#   B   C   D
A                
A2  2  B2  C2  D2
A4  4  B4  C4  D4

In [39]:
df3.iloc[1::2,:]

#   B   C   D
A                
A2  2  B2  C2  D2
A4  4  B4  C4  D4

In [40]:
df3.iloc[slice(1,None,2)]

#   B   C   D
A                
A2  2  B2  C2  D2
A4  4  B4  C4  D4

2. 使用索引数组

In [41]:
df3.iloc[[1,3]]

#   B   C   D
A                
A2  2  B2  C2  D2
A4  4  B4  C4  D4

In [42]:
df3.loc[['A1','A3']]

#   B   C   D
A                
A1  1  B1  C1  D1
A3  3  B3  C3  D3

In [43]:
df3.iloc[[3,2,1,0]]

#   B   C   D
A                
A4  4  B4  C4  D4
A3  3  B3  C3  D3
A2  2  B2  C2  D2
A1  1  B1  C1  D1

In [44]:
df3.loc[['A2', 'A1', 'A4', 'A3']]

#   B   C   D
A                
A2  2  B2  C2  D2
A1  1  B1  C1  D1
A4  4  B4  C4  D4
A3  3  B3  C3  D3

In [244]:
df3.take([0, 1, 3])

#   B   C   D
A                
A1  1  B1  C1  D1
A2  2  B2  C2  D2
A4  4  B4  C4  D4

In [248]:
df3.take([2, 1, 3])

#   B   C   D
A                
A3  3  B3  C3  D3
A2  2  B2  C2  D2
A4  4  B4  C4  D4

In [249]:
df3.take([-1, -2, -3])

#   B   C   D
A                
A4  4  B4  C4  D4
A3  3  B3  C3  D3
A2  2  B2  C2  D2

3. 使用布尔数组选择

In [45]:
df3.loc[[True, False, True, False]]

#   B   C   D
A                
A1  1  B1  C1  D1
A3  3  B3  C3  D3

In [46]:
df3.iloc[[True,True]]

#   B   C   D
A                
A1  1  B1  C1  D1
A2  2  B2  C2  D2

In [77]:
df3.loc[[True, True]]

#   B   C   D
A                
A1  1  B1  C1  D1
A2  2  B2  C2  D2

In [47]:
df3['#'] > 2

A
A1    False
A2    False
A3     True
A4     True
Name: #, dtype: bool

In [48]:
df3[df3['#'] > 2]

#   B   C   D
A                
A3  3  B3  C3  D3
A4  4  B4  C4  D4

In [49]:
df3[~(df3['B'] == 'B3')]

#   B   C   D
A                
A1  1  B1  C1  D1
A2  2  B2  C2  D2
A4  4  B4  C4  D4

In [50]:
df3[df3['B'] != 'B3']

#   B   C   D
A                
A1  1  B1  C1  D1
A2  2  B2  C2  D2
A4  4  B4  C4  D4

In [51]:
df3[df3.B =='B3']

#   B   C   D
A                
A3  3  B3  C3  D3

In [52]:
c1 = df3.B == 'B3'
c1

A
A1    False
A2    False
A3     True
A4    False
Name: B, dtype: bool

In [55]:
c2 = df3.C == 'C1'
c2

A
A1     True
A2    False
A3    False
A4    False
Name: C, dtype: bool

In [472]:
type(c1)

pandas.core.series.Series

In [473]:
type(c2)

pandas.core.series.Series

In [467]:
2 | 3

3

In [468]:
bin(2)

'0b10'

In [469]:
bin(3)

'0b11'

In [470]:
True | False

True

In [471]:
2 & 3

2

In [58]:
df3[c1 | c2]

#   B   C   D
A                
A1  1  B1  C1  D1
A3  3  B3  C3  D3

In [64]:
df3[(df3.B == 'B3') | (df3.C == 'C1')]

#   B   C   D
A                
A1  1  B1  C1  D1
A3  3  B3  C3  D3

In [61]:
df3[(df3['#'] > 2) & (df3.B =='B3')]

#   B   C   D
A                
A3  3  B3  C3  D3

In [85]:
condition = df3['#'].isin([2,3])
condition

A
A1    False
A2     True
A3     True
A4    False
Name: #, dtype: bool

In [86]:
df3[condition]

#   B   C   D
A                
A2  2  B2  C2  D2
A3  3  B3  C3  D3

In [87]:
df3.loc[condition]

#   B   C   D
A                
A2  2  B2  C2  D2
A3  3  B3  C3  D3

In [94]:
df

#   A   B   C   D
0  1  A1  B1  C1  D1
1  2  A2  B2  C2  D2
2  3  A3  B3  C3  D3
3  4  A4  B4  C4  D4

In [95]:
condition = df.A.isin(['A1','A3'])
condition

0     True
1    False
2     True
3    False
Name: A, dtype: bool

In [98]:
df.loc[condition]

#   A   B   C   D
0  1  A1  B1  C1  D1
2  3  A3  B3  C3  D3

3. 使用Query查询

In [478]:
df3.query("B < 'B2'")

#   B   C   D
A                
A1  1  B1  C1  D1

In [74]:
df3.query('A < "A4" and B > "B1"')

#   B   C   D
A                
A2  2  B2  C2  D2
A3  3  B3  C3  D3

#### 2. 选择列

##### （1）选择单列

In [164]:
df.iloc[:,0] # 首列

0    1
1    2
2    3
3    4
Name: #, dtype: int64

In [167]:
df.loc[:,'#']

0    1
1    2
2    3
3    4
Name: #, dtype: int64

In [171]:
df['#']

0    1
1    2
2    3
3    4
Name: #, dtype: int64

In [165]:
df.iloc[:,-1] #最后一列

0    D1
1    D2
2    D3
3    D4
Name: D, dtype: object

In [169]:
df.loc[:, 'D']

0    D1
1    D2
2    D3
3    D4
Name: D, dtype: object

In [483]:
r = df.get(['D']) #以列名为键
r

D
0  D1
1  D2
2  D3
3  D4

In [484]:
type(r)

pandas.core.frame.DataFrame

In [485]:
r = df.get('D')
r

0    D1
1    D2
2    D3
3    D4
Name: D, dtype: object

In [486]:
type(r)

pandas.core.series.Series

In [172]:
df['D']

0    D1
1    D2
2    D3
3    D4
Name: D, dtype: object

In [176]:
df.D

0    D1
1    D2
2    D3
3    D4
Name: D, dtype: object

In [161]:
df.iloc[:, df.shape[1] // 2] # 中间列

0    B1
1    B2
2    B3
3    B4
Name: B, dtype: object

In [174]:
df.iloc[:, len(df.columns) // 2]

0    B1
1    B2
2    B3
3    B4
Name: B, dtype: object

In [175]:
df['B']

0    B1
1    B2
2    B3
3    B4
Name: B, dtype: object

In [304]:
df.B

0    B1
1    B2
2    B3
3    B4
Name: B, dtype: object

In [124]:
df.loc[:,'B']

0    B1
1    B2
2    B3
3    B4
Name: B, dtype: object

In [127]:
df.iloc[:, 2]

0    B1
1    B2
2    B3
3    B4
Name: B, dtype: object

##### （2）选择多列

1. 使用切片选择

In [156]:
df.iloc[:,:2] # 前两列

#   A
0  1  A1
1  2  A2
2  3  A3
3  4  A4

In [159]:
df.iloc[:,-2:] # 后两列

C   D
0  C1  D1
1  C2  D2
2  C3  D3
3  C4  D4

In [143]:
df.loc[:, 'A':'C'] #中间三列

A   B   C
0  A1  B1  C1
1  A2  B2  C2
2  A3  B3  C3
3  A4  B4  C4

In [144]:
df.iloc[:, 1:4]

A   B   C
0  A1  B1  C1
1  A2  B2  C2
2  A3  B3  C3
3  A4  B4  C4

In [149]:
df.loc[:, slice('A','C',None)]

A   B   C
0  A1  B1  C1
1  A2  B2  C2
2  A3  B3  C3
3  A4  B4  C4

In [150]:
df.iloc[:, slice(1, 4, None)]

A   B   C
0  A1  B1  C1
1  A2  B2  C2
2  A3  B3  C3
3  A4  B4  C4

In [152]:
df.iloc[:,::2] # 偶数列

#   B   D
0  1  B1  D1
1  2  B2  D2
2  3  B3  D3
3  4  B4  D4

In [153]:
df.iloc[:,1::2] # 奇数列

A   C
0  A1  C1
1  A2  C2
2  A3  C3
3  A4  C4

In [151]:
df.iloc[:,::-1] # 列逆序

D   C   B   A  #
0  D1  C1  B1  A1  1
1  D2  C2  B2  A2  2
2  D3  C3  B3  A3  3
3  D4  C4  B4  A4  4

In [177]:
df.iloc[::-1, ::-1] # 行列逆序

D   C   B   A  #
3  D4  C4  B4  A4  4
2  D3  C3  B3  A3  3
1  D2  C2  B2  A2  2
0  D1  C1  B1  A1  1

2. 使用索引和列名数组选择

In [181]:
df.iloc[:,[1,3]]

A   C
0  A1  C1
1  A2  C2
2  A3  C3
3  A4  C4

In [182]:
df.loc[:, ['A','C']]

A   C
0  A1  C1
1  A2  C2
2  A3  C3
3  A4  C4

In [183]:
df[['A','C']] # 快捷方式

A   C
0  A1  C1
1  A2  C2
2  A3  C3
3  A4  C4

In [187]:
df.get(['A','C']) # 以列名为键

A   C
0  A1  C1
1  A2  C2
2  A3  C3
3  A4  C4

In [137]:
df[['A']]

A
0  A1
1  A2
2  A3
3  A4

In [133]:
df.iloc[:,[1,4]]

A   D
0  A1  D1
1  A2  D2
2  A3  D3
3  A4  D4

In [251]:
df.take([1, 4], axis=1) # 按列索引提取

A   D
0  A1  D1
1  A2  D2
2  A3  D3
3  A4  D4

3. 使用条件数组选择列

In [219]:
df.loc[:, [False, True, True, False, True]]

A   B   D
0  A1  B1  D1
1  A2  B2  D2
2  A3  B3  D3
3  A4  B4  D4

#### 3. 选择行和列

1. 使用索引和切片

In [487]:
r = df.loc[1,'B']
r

'B2'

In [488]:
type(r)

str

In [195]:
df.iloc[1, 2]

'B2'

In [196]:
df['B'][1]

'B2'

In [213]:
df.iloc[1:3, 1:4] # 切片

A   B   C
1  A2  B2  C2
2  A3  B3  C3

In [210]:
df.loc[1:2,'A':'C'] # 切片

A   B   C
1  A2  B2  C2
2  A3  B3  C3

In [214]:
df.iloc[1:3, [1, 3]] # 行切片+列索引数组

A   C
1  A2  C2
2  A3  C3

In [211]:
df.loc[1:2, ['A','C']]  # 行切片+列名数组

A   C
1  A2  C2
2  A3  C3

2. 使用布尔数组

In [220]:
df.loc[1:2, [True, False, True, True, False]] # 行切片+使用布尔数组

#   B   C
1  2  B2  C2
2  3  B3  C3

In [221]:
df.iloc[1:3, [False, True, False, True]]

A   C
1  A2  C2
2  A3  C3

3. 使用过滤器

In [233]:
df.filter(items=['A','C'], axis=1)[1:] # 使用列过滤器

A   C
1  A2  C2
2  A3  C3
3  A4  C4

In [489]:
df.filter(like='A', axis=0) # 使用行过滤器

Empty DataFrame
Columns: [#, A, B, C, D]
Index: []

4. 使用截取

In [263]:
df.truncate(before=2, after=3) # 截取2～3行

#   A   B   C   D
2  3  A3  B3  C3  D3
3  4  A4  B4  C4  D4

In [266]:
df.truncate(before=2, after=3, axis='index')

#   A   B   C   D
2  3  A3  B3  C3  D3
3  4  A4  B4  C4  D4

In [265]:
df.truncate(before='A', after='C', axis=1) # 截取A～C列

A   B   C
0  A1  B1  C1
1  A2  B2  C2
2  A3  B3  C3
3  A4  B4  C4

In [267]:
df.truncate(before='A', after='C', axis='columns')

A   B   C
0  A1  B1  C1
1  A2  B2  C2
2  A3  B3  C3
3  A4  B4  C4

5. 使用随机采样

In [276]:
df.sample(n=3, random_state=1)

#   A   B   C   D
3  4  A4  B4  C4  D4
2  3  A3  B3  C3  D3
0  1  A1  B1  C1  D1

In [282]:
df.sample(frac=0.4)

#   A   B   C   D
2  3  A3  B3  C3  D3
3  4  A4  B4  C4  D4

In [278]:
df[['A','C']].sample(n=2, random_state=1)

A   C
3  A4  C4
2  A3  C3

In [284]:
df.sample(n=2, random_state=2, axis=1)[2:]

B   D
2  B3  D3
3  B4  D4

### 数据拆分

将一个数据集拆分为多个数据集

#### 1. 按行拆分

In [505]:
df

#   A   B   C   D
0  1  A1  B1  C1  D1
1  2  A2  B2  SS  D2
2  3  A3  B3  C3  D3
3  4  A4  B4  C4  D4

In [506]:
df1 = df[0:2].copy()
df1

#   A   B   C   D
0  1  A1  B1  C1  D1
1  2  A2  B2  SS  D2

In [507]:
df1.loc[1, 'A']

'A2'

In [509]:
df1.loc[1, 'A'] = '88'
df1

#   A   B   C   D
0  1  A1  B1  C1  D1
1  2  88  B2  SS  D2

In [510]:
df

#   A   B   C   D
0  1  A1  B1  C1  D1
1  2  A2  B2  SS  D2
2  3  A3  B3  C3  D3
3  4  A4  B4  C4  D4

In [289]:
df2 = df[2:]
df2

#   A   B   C   D
2  3  A3  B3  C3  D3
3  4  A4  B4  C4  D4

#### 2. 按列拆分

In [290]:
df

#   A   B   C   D
0  1  A1  B1  C1  D1
1  2  A2  B2  C2  D2
2  3  A3  B3  C3  D3
3  4  A4  B4  C4  D4

In [293]:
df_left = df[['A', 'B']]
df_left

A   B
0  A1  B1
1  A2  B2
2  A3  B3
3  A4  B4

In [295]:
df_right = df[['C','D']]
df_right

C   D
0  C1  D1
1  C2  D2
2  C3  D3
3  C4  D4

In [296]:
df_right.set_index('C')

D
C     
C1  D1
C2  D2
C3  D3
C4  D4

In [297]:
df_right

C   D
0  C1  D1
1  C2  D2
2  C3  D3
3  C4  D4

In [298]:
df_left

A   B
0  A1  B1
1  A2  B2
2  A3  B3
3  A4  B4

In [299]:
df_right

C   D
0  C1  D1
1  C2  D2
2  C3  D3
3  C4  D4

### 数据拼接

#### 1. 按行拼接

In [300]:
df1

#   A   B   C   D
0  1  A1  B1  C1  D1
1  2  A2  B2  C2  D2

In [301]:
df2

#   A   B   C   D
2  3  A3  B3  C3  D3
3  4  A4  B4  C4  D4

In [302]:
df1.append(df2)

#   A   B   C   D
0  1  A1  B1  C1  D1
1  2  A2  B2  C2  D2
2  3  A3  B3  C3  D3
3  4  A4  B4  C4  D4

In [303]:
pd.concat([df1, df2])

#   A   B   C   D
0  1  A1  B1  C1  D1
1  2  A2  B2  C2  D2
2  3  A3  B3  C3  D3
3  4  A4  B4  C4  D4

#### 2. 按列拼接

##### merge合并

In [304]:
df_left

A   B
0  A1  B1
1  A2  B2
2  A3  B3
3  A4  B4

In [305]:
df_right

C   D
0  C1  D1
1  C2  D2
2  C3  D3
3  C4  D4

In [312]:
df_merged = df_left.merge(df_right, left_index=True, right_index=True)
df_merged

A   B   C   D
0  A1  B1  C1  D1
1  A2  B2  C2  D2
2  A3  B3  C3  D3
3  A4  B4  C4  D4

重建索引（如果索引无法连接）

In [313]:
df_left_A = df_left.set_index('A')
df_left_A

B
A     
A1  B1
A2  B2
A3  B3
A4  B4

In [316]:
df_right_C = df_right.set_index('C')
df_right_C

D
C     
C1  D1
C2  D2
C3  D3
C4  D4

In [318]:
df_left_A.merge(df_right_C, left_index=True, right_index=True)

Empty DataFrame
Columns: [B, D]
Index: []

In [319]:
df_left_indexed = df_left_A.reset_index()
df_left_indexed

A   B
0  A1  B1
1  A2  B2
2  A3  B3
3  A4  B4

In [320]:
df_right_indexed = df_right_C.reset_index()
df_right_indexed

C   D
0  C1  D1
1  C2  D2
2  C3  D3
3  C4  D4

2. 左右合并

In [321]:
df_merged = df_left_indexed.merge(df_right_indexed, left_index=True, right_index=True)
df_merged

A   B   C   D
0  A1  B1  C1  D1
1  A2  B2  C2  D2
2  A3  B3  C3  D3
3  A4  B4  C4  D4

In [322]:
df_merged.set_index('A')

B   C   D
A             
A1  B1  C1  D1
A2  B2  C2  D2
A3  B3  C3  D3
A4  B4  C4  D4

##### concat 拼接

In [323]:
pd.concat([df_left, df_right], sort=False)

A    B    C    D
0   A1   B1  NaN  NaN
1   A2   B2  NaN  NaN
2   A3   B3  NaN  NaN
3   A4   B4  NaN  NaN
0  NaN  NaN   C1   D1
1  NaN  NaN   C2   D2
2  NaN  NaN   C3   D3
3  NaN  NaN   C4   D4

In [324]:
df_concat = pd.concat([df_left_indexed, df_right_indexed], axis=1)
df_concat

A   B   C   D
0  A1  B1  C1  D1
1  A2  B2  C2  D2
2  A3  B3  C3  D3
3  A4  B4  C4  D4

In [325]:
df_concat.set_index('A')

B   C   D
A             
A1  B1  C1  D1
A2  B2  C2  D2
A3  B3  C3  D3
A4  B4  C4  D4

##### join连接

In [326]:
df_left

A   B
0  A1  B1
1  A2  B2
2  A3  B3
3  A4  B4

In [327]:
df_right

C   D
0  C1  D1
1  C2  D2
2  C3  D3
3  C4  D4

In [328]:
df_joined = df_left.join(df_right)
df_joined

A   B   C   D
0  A1  B1  C1  D1
1  A2  B2  C2  D2
2  A3  B3  C3  D3
3  A4  B4  C4  D4

In [330]:
df_left_indexed = df_left_A.reset_index()
df_left_indexed

A   B
0  A1  B1
1  A2  B2
2  A3  B3
3  A4  B4

In [331]:
df_right_indexed = df_right_C.reset_index()
df_right_indexed

C   D
0  C1  D1
1  C2  D2
2  C3  D3
3  C4  D4

In [332]:
df_joined = df_left_indexed.join(df_right_indexed)
df_joined

A   B   C   D
0  A1  B1  C1  D1
1  A2  B2  C2  D2
2  A3  B3  C3  D3
3  A4  B4  C4  D4

In [333]:
df_joined.set_index('A')

B   C   D
A             
A1  B1  C1  D1
A2  B2  C2  D2
A3  B3  C3  D3
A4  B4  C4  D4

##### assign添加列

In [337]:
df_left.assign(C=df_right.C, D=df_right.D)

A   B   C   D
0  A1  B1  C1  D1
1  A2  B2  C2  D2
2  A3  B3  C3  D3
3  A4  B4  C4  D4

In [339]:
df_left.assign(C=df_right['C'], D=df_right['D'])

A   B   C   D
0  A1  B1  C1  D1
1  A2  B2  C2  D2
2  A3  B3  C3  D3
3  A4  B4  C4  D4

#### 3. 内容合并（combine）

In [514]:
df_left.combine(df_right, func=lambda a, b: a + b, fill_value='-', overwrite=True )

A    B    C    D
0  A1-  B1-  -C1  -D1
1  A2-  B2-  -C2  -D2
2  A3-  B3-  -C3  -D3
3  A4-  B4-  -C4  -D4

In [347]:
df_left_3 = df.iloc[:,:3]
df_left_3

#   A   B
0  1  A1  B1
1  2  A2  B2
2  3  A3  B3
3  4  A4  B4

In [348]:
df_right_3 = df.iloc[:,-3:]
df_right_3

B   C   D
0  B1  C1  D1
1  B2  C2  D2
2  B3  C3  D3
3  B4  C4  D4

In [349]:
df_left_3.combine(df_right_3, func=lambda a,b: a + b)

#    A     B   C   D
0 NaN  NaN  B1B1 NaN NaN
1 NaN  NaN  B2B2 NaN NaN
2 NaN  NaN  B3B3 NaN NaN
3 NaN  NaN  B4B4 NaN NaN

In [351]:
df_l = df.copy()
df_r = df.copy()
df_r

#   A   B   C   D
0  1  A1  B1  C1  D1
1  2  A2  B2  C2  D2
2  3  A3  B3  C3  D3
3  4  A4  B4  C4  D4

In [355]:
df_l.combine(df_r, func=lambda a, b: a + b)

#     A     B     C     D
0  2  A1A1  B1B1  C1C1  D1D1
1  4  A2A2  B2B2  C2C2  D2D2
2  6  A3A3  B3B3  C3C3  D3D3
3  8  A4A4  B4B4  C4C4  D4D4

### 数据离散化

In [362]:
!cat data/eg02.csv

Id,Name,Score
201912001,Zhang,85
201912002,Lee,56
201912003,Wang,78
201912004,Zhao,62
201912005,Qian,94
201912006,Sun,100

In [363]:
df_scores = pd.read_csv('data/eg02.csv')
df_scores

Id   Name  Score
0  201912001  Zhang     85
1  201912002    Lee     56
2  201912003   Wang     78
3  201912004   Zhao     62
4  201912005   Qian     94
5  201912006    Sun    100

In [364]:
grades = [0, 60, 70, 80, 90, 100]
grades

[0, 60, 70, 80, 90, 100]

In [365]:
df_scores['Score']

0     85
1     56
2     78
3     62
4     94
5    100
Name: Score, dtype: int64

In [516]:
pd.cut(df_scores['Score'], grades)

0     (80, 90]
1      (0, 60]
2     (70, 80]
3     (60, 70]
4    (90, 100]
5    (90, 100]
Name: Score, dtype: category
Categories (5, interval[int64]): [(0, 60] < (60, 70] < (70, 80] < (80, 90] < (90, 100]]

In [367]:
labels = list("EDCBA")
df_scores['Grade'] = pd.cut(df_scores['Score'], grades, labels=labels)

In [368]:
df_scores

Id   Name  Score Grade
0  201912001  Zhang     85     B
1  201912002    Lee     56     E
2  201912003   Wang     78     C
3  201912004   Zhao     62     D
4  201912005   Qian     94     A
5  201912006    Sun    100     A

### 数据二元化

#### 独热编码（One-Hot Encoding） 

In [369]:
!cat data/eg03.csv

#,Color,Size
1,Red,S
2,Green,M
3,Blue,L
4,Green,XL
5,Red,M
6,Blue,XXL

In [370]:
df_shirts = pd.read_csv('data/eg03.csv')
df_shirts

#  Color Size
0  1    Red    S
1  2  Green    M
2  3   Blue    L
3  4  Green   XL
4  5    Red    M
5  6   Blue  XXL

In [371]:
df_onehot = pd.get_dummies(df_shirts, columns=['Color', 'Size'])
df_onehot

#  Color_Blue  Color_Green  Color_Red  Size_L  Size_M  Size_S  Size_XL  \
0  1           0            0          1       0       0       1        0   
1  2           0            1          0       0       1       0        0   
2  3           1            0          0       1       0       0        0   
3  4           0            1          0       0       0       0        1   
4  5           0            0          1       0       1       0        0   
5  6           1            0          0       0       0       0        0   

   Size_XXL  
0         0  
1         0  
2         0  
3         0  
4         0  
5         1

In [372]:
df_onehot = pd.get_dummies(df_shirts, prefix='',prefix_sep="",\
                           columns=['Color', 'Size'])
df_onehot

#  Blue  Green  Red  L  M  S  XL  XXL
0  1     0      0    1  0  0  1   0    0
1  2     0      1    0  0  1  0   0    0
2  3     1      0    0  1  0  0   0    0
3  4     0      1    0  0  0  0   1    0
4  5     0      0    1  0  1  0   0    0
5  6     1      0    0  0  0  0   0    1